export const metadata = {
  title: "Terms of Service | Freakout.lol",
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-2xl px-4 py-16">
      <h1 className="text-3xl font-semibold text-foreground">Terms of Service</h1>
      <p className="mt-4 text-foreground/60 text-sm">Last updated: May 26, 2026</p>

      <div className="mt-8 space-y-6 text-foreground/80 text-sm leading-relaxed">
        <section>
          <h2 className="text-lg font-medium text-foreground">
            1. Acceptance of Terms
          </h2>
          <p className="mt-2">
            By accessing or using Freakout (&quot;the Service&quot;) at freakout.lol, you
            agree to be bound by these Terms of Service. If you do not agree, do not use
            the Service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-medium text-foreground">
            2. Description of Service
          </h2>
          <p className="mt-2">
            Freakout provides AI-powered due diligence and document analysis tools. The
            Service processes documents you upload and generates structured analysis,
            insights, and reports.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-medium text-foreground">3. Accounts</h2>
          <p className="mt-2">
            You must provide accurate information when creating an account. You are
            responsible for maintaining the security of your account credentials and for
            all activity under your account.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-medium text-foreground">4. Acceptable Use</h2>
          <p className="mt-2">You agree not to:</p>
          <ul className="mt-2 list-disc space-y-1 pl-5">
            <li>Use the Service for any unlawful purpose</li>
            <li>Upload malicious files or attempt to compromise the platform</li>
            <li>Reverse-engineer or attempt to extract the underlying models or algorithms</li>
            <li>Share account access with unauthorized parties</li>
            <li>Exceed reasonable usage limits or abuse the Service</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-medium text-foreground">5. Your Content</h2>
          <p className="mt-2">
            You retain ownership of all documents and data you upload. By using the
            Service, you grant us a limited license to process your content solely for the
            purpose of providing the Service. We do not use your content to train AI
            models.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-medium text-foreground">
            6. AI-Generated Output
          </h2>
          <p className="mt-2">
            Analysis and reports generated by the Service are provided for informational
            purposes only. They do not constitute professional advice (legal, financial,
            or otherwise). You are responsible for independently verifying any conclusions
            before making decisions based on them.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-medium text-foreground">
            7. Payment and Billing
          </h2>
          <p className="mt-2">
            Paid plans are billed in advance on a recurring basis. You may cancel at any
            time; access continues until the end of the current billing period. Refunds
            are provided at our discretion.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-medium text-foreground">
            8. Service Availability
          </h2>
          <p className="mt-2">
            We strive to maintain high availability but do not guarantee uninterrupted
            access. We may perform maintenance, updates, or modifications to the Service
            at any time.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-medium text-foreground">
            9. Limitation of Liability
          </h2>
          <p className="mt-2">
            To the maximum extent permitted by law, Freakout shall not be liable for any
            indirect, incidental, special, or consequential damages arising from your use
            of the Service. Our total liability is limited to the amount you paid us in
            the 12 months preceding the claim.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-medium text-foreground">10. Termination</h2>
          <p className="mt-2">
            We may suspend or terminate your access if you violate these terms. You may
            delete your account at any time. Upon termination, your data will be deleted
            in accordance with our Privacy Policy.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-medium text-foreground">
            11. Changes to Terms
          </h2>
          <p className="mt-2">
            We may update these terms from time to time. Continued use of the Service
            after changes constitutes acceptance. We will notify you of material changes
            via email or in-app notice.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-medium text-foreground">12. Contact</h2>
          <p className="mt-2">
            Questions about these terms? Reach us at{" "}
            <a
              href="mailto:general@freakout.ai"
              className="text-primary hover:underline"
            >
              general@freakout.ai
            </a>
            .
          </p>
        </section>
      </div>
    </div>
  );
}
