import type { AppLabels } from "@/labels/types";

export const appLabels: AppLabels["app"] = {
  dashboard: {
    heading: "Dashboard",
    description: "Welcome back.",
    projectsHeading: "Projects",
    createProjectCta: "Create project",
    statusHeading: "Status",
    inspectCta: "Inspect",
    statuses: {
      draft: "Draft",
      inprogress: "In Progress",
      reviewed: "Reviewed",
      complete: "Complete",
      rejected: "Rejected",
    },
  },
  projectInspect: {
    heading: "Project",
    statusLabel: "Status",
    createdLabel: "Created",
    idLabel: "Project ID",
    copyIdAriaLabel: "Copy project ID",
    copySuccessToast: "Project ID copied to clipboard.",
    copyErrorToast: "Could not copy project ID.",
    deleteProjectCta: "Delete project",
    deleteProjectConfirm:
      "Delete this project? Files, diligence jobs, and findings will be removed permanently.",
    deleteProjectInProgress: "Deleting...",
    deleteProjectSuccessToast: "Project deleted.",
    deleteProjectErrorToast: "Failed to delete project.",
    documentsHeading: "Files",
    fileInputLabel: "Upload files",
    uploadInProgress: "Uploading...",
    dropzoneTitle: "Drag and drop files to upload",
    dropzoneHint: "Files upload automatically after drop.",
    uploadQueueHeading: "Upload progress",
    uploadStatusQueued: "Queued",
    uploadStatusUploading: "Uploading",
    uploadStatusUploaded: "Uploaded",
    uploadStatusFailed: "Failed",
    emptyDocuments: "No files uploaded yet.",
    loadingDocuments: "Loading files...",
    loadError: "Failed to load files.",
    uploadError: "Failed to upload file.",
    viewFileCta: "View",
    deleteFileCta: "Delete",
    deleteInProgress: "Deleting...",
    deleteError: "Failed to delete file.",
    reprocessFileCta: "Re-process",
    reprocessInProgress: "Queueing...",
    reprocessError: "Failed to queue file for re-processing.",
    fileStatusLabel: "File status",
    fileProcessingStatuses: {
      QUEUED: "Queued",
      PROCESSING: "Processing",
      PROCESSED: "Processed",
      FAILED: "Failed",
    },
    beDiligentCta: "Be Diligent",
    providerSelectionLabel: "Provider",
    modelInputLabel: "Model",
    modelInputPlaceholder: "gpt-4o-mini",
    fallbackProvidersLabel: "Fallback providers",
    retryDiligenceCta: "Retry diligence",
    cancelDiligenceCta: "Cancel diligence",
    cancelDiligenceConfirm: "Cancel the running diligence workflow?",
    cancelDiligenceToast: "Diligence cancelled.",
    cancelDiligenceErrorToast: "Failed to cancel diligence.",
    diligenceProgressHeading: "Diligence worker",
    diligenceStatusLabel: "Job status",
    diligenceCurrentStageLabel: "Current stage",
    diligenceJobIdLabel: "Job ID",
    diligenceTokenUsageLabel: "Token usage",
    diligenceCostEstimateLabel: "Estimated cost",
    diligenceLastErrorLabel: "Last error",
    diligenceNoJobMessage: "No diligence job has started yet.",
    diligenceJobCreatedToast: "Due diligence job initialized.",
    diligenceRunningToast: "Diligence workflow running.",
    diligenceCompletedToast: "Due diligence job completed.",
    diligenceRetryToast: "Diligence retry started.",
    diligenceRetryErrorToast: "Failed to retry due diligence.",
    diligenceStatuses: {
      QUEUED: "Queued",
      RUNNING: "Running",
      WAITING_INPUT: "Waiting for Input",
      COMPLETED: "Completed",
      FAILED: "Failed",
      CANCELED: "Canceled",
    },
    diligenceStages: {
      DOCUMENT_EXTRACTION: "Document Extraction",
      DOCUMENT_CLASSIFICATION: "Document Classification",
      EVIDENCE_INDEXING: "Evidence Indexing",
      ENTITY_EXTRACTION: "Entity Extraction",
      CLAIM_EXTRACTION: "Claim Extraction",
      CORROBORATION: "Corroboration",
      Q1_IDENTITY_AND_OWNERSHIP: "Q1: Identity & Ownership",
      Q2_PRODUCT_AND_TECHNOLOGY: "Q2: Product & Technology",
      Q3_MARKET_AND_TRACTION: "Q3: Market & Traction",
      Q4_EXECUTION_CAPABILITY: "Q4: Execution Capability",
      Q5_BUSINESS_MODEL_VIABILITY: "Q5: Business Model Viability",
      Q6_RISK_ANALYSIS: "Q6: Risk Analysis",
      Q7_EVIDENCE_QUALITY: "Q7: Evidence Quality",
      Q8_FAILURE_MODES_AND_FRAGILITY: "Q8: Failure Modes & Fragility",
      OPEN_QUESTIONS: "Open Questions",
      EXECUTIVE_SUMMARY: "Executive Summary",
      FINAL_REPORT: "Final Report",
    },
    setupApiKeysMessage: "Add at least one API key in Settings to run due diligence.",
    setupApiKeysToast: "No API keys found. Opening Settings in a new tab.",
    setupApiKeysNotification:
      "No API keys found. Add one in Settings to run due diligence.",
    setupApiKeysLinkCta: "Go to Settings",
    diligenceStartToast: "Due diligence started.",
    insightsHeading: "Reviewed insights",
    insightsEmpty: "No reviewed insights yet. Run due diligence to generate findings.",
    insightsRisksHeading: "Top risks",
    insightsClaimsHeading: "Key claims",
    insightsEntitiesHeading: "Core entities",
    insightsContradictionsHeading: "Contradictions",
  },
  insights: {
    heading: "Insights",
    description: "All findings, claims, entities, and contradictions from the latest completed diligence run.",
    empty: "No insights available. Complete a diligence run to generate findings.",
    findingsHeading: "Findings",
    claimsHeading: "Claims",
    entitiesHeading: "Entities",
    contradictionsHeading: "Contradictions",
    jobInfoHeading: "Job summary",
    stagesHeading: "Pipeline stages",
    confidenceLabel: "Confidence",
    statusLabel: "Status",
    typeLabel: "Type",
    modelLabel: "Model",
    providerLabel: "Provider",
    tokensLabel: "Tokens",
    costLabel: "Est. cost",
    createdLabel: "Created",
    completedLabel: "Completed",
    findingTypes: {
      RISK: "Risk",
      OPPORTUNITY: "Opportunity",
      WARNING: "Warning",
      OBSERVATION: "Observation",
    },
    claimStatuses: {
      SUPPORTED: "Supported",
      CONTRADICTED: "Contradicted",
      INCONCLUSIVE: "Inconclusive",
    },
  },
  reports: {
    heading: "Reports",
    description: "Generated reports and export bundles from diligence runs.",
    empty: "No reports generated yet. Complete a diligence run to produce reports.",
    tableHeadType: "Type",
    tableHeadStage: "Stage",
    tableHeadFormat: "Format",
    tableHeadSize: "Size",
    tableHeadDate: "Generated",
    tableHeadJobStatus: "Job status",
    tableHeadActions: "Actions",
    viewCta: "View",
    artifactTypes: {
      GENERATED_REPORT: "Report",
      EXPORT_BUNDLE: "Export bundle",
      EVIDENCE_MAP: "Evidence map",
    },
  },
  enquiries: {
    heading: "Enquiries",
    description: "Investor Q&A grounded in the completed diligence report and source files.",
    lockedTitle: "Enquiries unlock after a completed report.",
    lockedDescription:
      "Finish due diligence and generate a report first. Then you can ask investor-style follow-up questions here.",
    introMessage:
      "Ask me anything about this diligence report and the uploaded documents. I will answer using available evidence and call out any gaps.",
    sampleQuestionsHeading: "Try asking:",
    sampleQuestionOne: "What is the biggest risk that could break this deal?",
    sampleQuestionTwo: "Which claims have weak supporting evidence?",
    sampleQuestionThree: "What should we ask founders before IC?",
    sendCta: "Ask agent",
    sendingCta: "Analyzing…",
    investorLabel: "Investor",
    agentLabel: "Diligence agent",
    agentThinking: "Reviewing report and evidence…",
    sourcesHeading: "Evidence used",
    errorPrefix: "Enquiry failed",
    genericError: "Could not generate an answer for that question.",
    placeholder: "Ask a follow-up about the report or uploaded data...",
  },
  projectCreation: {
    heading: "Create project",
    description: "Name your project to start qualification.",
    nameLabel: "Project name",
    namePlaceholder: "Acme diligence workspace",
    filesLabel: "Files",
    filesHint: "You can upload one or more files now.",
    submitCta: "Create project",
    assistanceGoalLabel: "Workflow",
    assistanceGoalHint: "Select a knowledge graph workflow to guide evidence gathering and output generation.",
    noGoalLabel: "No workflow",
    noGoalHint: "Upload documents and run diligence without a structured workflow.",
  },
  settings: {
    heading: "Settings",
    description: "Manage your firm workspace and provider configuration.",
    firmHeading: "Firm workspace",
    firmDescription:
      "Your active firm controls project access, billing, graph workflows, and role-based permissions.",
    firmNameLabel: "Firm",
    firmRoleLabel: "Role",
    firmPlanLabel: "Plan",
    firmBillingLabel: "Billing",
    firmPermissionsLabel: "Enabled permissions",
    membersHeading: "Members",
    membersDescription:
      "Add existing users to this firm and manage their workspace role.",
    memberEmailLabel: "Email",
    memberRoleLabel: "Role",
    memberAddCta: "Add member",
    memberUpdateCta: "Update role",
    auditHeading: "Audit log",
    auditDescription:
      "Recent privileged actions in this firm workspace.",
    auditEmpty: "No audit events recorded yet.",
    apiKeysHeading: "AI Provider Keys",
    apiKeysDescription:
      "Bring your own API keys to power AI features. Keys are encrypted at rest with AES-256 and never returned to the browser.",
    encryptionNote:
      "Keys are stored encrypted. Only you can use them; they are never shared or logged.",
    billingHeading: "Billing & plan",
    billingDescription:
      "Manage your subscription, view usage, and upgrade your plan.",
    billingPlanLabel: "Plan",
    billingStatusLabel: "Status",
    billingPeriodEndLabel: "Renews",
    billingUsageHeading: "This month's usage",
    billingUploadsLabel: "Uploads",
    billingRunsLabel: "Diligence runs",
    billingExportsLabel: "Exports",
    billingUpgradeCta: "Upgrade plan",
    billingManageCta: "Manage billing",
    billingNoSubscription: "No active subscription. Upgrade to unlock higher limits.",
  },
  draft: {
    heading: "Output draft",
    description: "Source-backed draft generated from completed diligence.",
    noDataHeading: "No draft available",
    noDataDescription: "Complete a diligence run with a workflow selected to generate a draft.",
    sectionsLabel: "Sections covered",
    confidenceLabel: "Avg. confidence",
    openQuestionsLabel: "Open questions",
    openQuestionsHeading: "Open questions for founders",
    keyClaimsHeading: "Key claims",
    findingsHeading: "Findings",
    gapsHeading: "Evidence gaps",
  },
  graphWorkflow: {
    enabledGraphsHeading: "Knowledge graph workflows",
    enabledGraphsDescription: "Enable structured workflows for your firm. Enabled workflows appear as options when creating new projects.",
    availableGraphsHeading: "Available workflows",
    noGraphsAvailable: "No published workflows are available yet.",
    enableCta: "Enable",
    disableCta: "Disable",
    enabledBadge: "Enabled",
    requirementsCount: "requirements",
    goalLabel: "Workflow",
    goalNone: "None",
    requirementsHeading: "Evidence requirements",
    requirementsEmpty: "No requirements defined for this workflow.",
    gapsHeading: "Evidence gaps",
    gapsEmpty: "All requirements are satisfied.",
    gapPriorityHigh: "High",
    gapPriorityMedium: "Medium",
    gapPriorityLow: "Low",
    mappingStatusOpen: "Open",
    mappingStatusPartial: "Partial",
    mappingStatusSatisfied: "Satisfied",
    mappingStatusWaived: "Waived",
    markSatisfiedCta: "Mark satisfied",
    markWaivedCta: "Waive",
    outputTemplatesHeading: "Output templates",
    outputTemplatesEmpty: "No output templates defined.",
    adminHeading: "Graph Studio",
    adminDescription: "Create, version, and publish knowledge graph workflows.",
    adminGraphsHeading: "Graph definitions",
    adminPublishCta: "Publish",
    adminDeprecateCta: "Deprecate",
    adminStatusDraft: "Draft",
    adminStatusPublished: "Published",
    adminStatusDeprecated: "Deprecated",
  },
};
