export type SupportedLocale = "en";

export type MetricLabel = {
  label: string;
  value: string;
};

export type WorkflowStepLabel = {
  title: string;
  description: string;
};

export type MarketingLabels = {
  hero: {
    badge: string;
    title: string;
    description: string;
    trialCta: string;
    demoCta: string;
    segmentLabels: string[];
  };
  metrics: MetricLabel[];
  workflow: {
    heading: string;
    steps: WorkflowStepLabel[];
  };
  coverage: {
    heading: string;
    description: string;
    items: string[];
    outcomesTitle: string;
    outcomesParagraphs: string[];
  };
  taxonomy: {
    heading: string;
    description: string;
    items: string[];
  };
  cta: {
    heading: string;
    description: string;
    createWorkspaceCta: string;
    contactSalesCta: string;
    footnote: string;
  };
};

export type AppLabels = {
  marketing: MarketingLabels;
  docs: {
    heading: string;
    description: string;
    sidebarEyebrow: string;
    indexEyebrow: string;
    indexHeading: string;
    indexDescription: string;
    allDocsCta: string;
    sourceLabel: string;
    noSummaryFallback: string;
  };
  app: {
    dashboard: {
      heading: string;
      description: string;
      projectsHeading: string;
      createProjectCta: string;
      statusHeading: string;
      inspectCta: string;
      statuses: {
        draft: string;
        inprogress: string;
        reviewed: string;
        complete: string;
        rejected: string;
      };
    };
    projectInspect: {
      heading: string;
      statusLabel: string;
      createdLabel: string;
      idLabel: string;
      copyIdAriaLabel: string;
      copySuccessToast: string;
      copyErrorToast: string;
      deleteProjectCta: string;
      deleteProjectConfirm: string;
      deleteProjectInProgress: string;
      deleteProjectSuccessToast: string;
      deleteProjectErrorToast: string;
      documentsHeading: string;
      fileInputLabel: string;
      uploadInProgress: string;
      dropzoneTitle: string;
      dropzoneHint: string;
      uploadQueueHeading: string;
      uploadStatusQueued: string;
      uploadStatusUploading: string;
      uploadStatusUploaded: string;
      uploadStatusFailed: string;
      emptyDocuments: string;
      loadingDocuments: string;
      loadError: string;
      uploadError: string;
      viewFileCta: string;
      deleteFileCta: string;
      deleteInProgress: string;
      deleteError: string;
      reprocessFileCta: string;
      reprocessInProgress: string;
      reprocessError: string;
      fileStatusLabel: string;
      fileProcessingStatuses: {
        QUEUED: string;
        PROCESSING: string;
        PROCESSED: string;
        FAILED: string;
      };
      beDiligentCta: string;
      providerSelectionLabel: string;
      modelInputLabel: string;
      modelInputPlaceholder: string;
      fallbackProvidersLabel: string;
      retryDiligenceCta: string;
      cancelDiligenceCta: string;
      cancelDiligenceConfirm: string;
      cancelDiligenceToast: string;
      cancelDiligenceErrorToast: string;
      diligenceProgressHeading: string;
      diligenceStatusLabel: string;
      diligenceCurrentStageLabel: string;
      diligenceJobIdLabel: string;
      diligenceTokenUsageLabel: string;
      diligenceCostEstimateLabel: string;
      diligenceLastErrorLabel: string;
      diligenceNoJobMessage: string;
      diligenceJobCreatedToast: string;
      diligenceRunningToast: string;
      diligenceCompletedToast: string;
      diligenceRetryToast: string;
      diligenceRetryErrorToast: string;
      diligenceStatuses: {
        QUEUED: string;
        RUNNING: string;
        WAITING_INPUT: string;
        COMPLETED: string;
        FAILED: string;
        CANCELED: string;
      };
      diligenceStages: {
        DOCUMENT_EXTRACTION: string;
        DOCUMENT_CLASSIFICATION: string;
        EVIDENCE_INDEXING: string;
        ENTITY_EXTRACTION: string;
        CLAIM_EXTRACTION: string;
        CORROBORATION: string;
        Q1_IDENTITY_AND_OWNERSHIP: string;
        Q2_PRODUCT_AND_TECHNOLOGY: string;
        Q3_MARKET_AND_TRACTION: string;
        Q4_EXECUTION_CAPABILITY: string;
        Q5_BUSINESS_MODEL_VIABILITY: string;
        Q6_RISK_ANALYSIS: string;
        Q7_EVIDENCE_QUALITY: string;
        Q8_FAILURE_MODES_AND_FRAGILITY: string;
        OPEN_QUESTIONS: string;
        EXECUTIVE_SUMMARY: string;
        FINAL_REPORT: string;
      };
      setupApiKeysMessage: string;
      setupApiKeysToast: string;
      setupApiKeysNotification: string;
      setupApiKeysLinkCta: string;
      diligenceStartToast: string;
      insightsHeading: string;
      insightsEmpty: string;
      insightsRisksHeading: string;
      insightsClaimsHeading: string;
      insightsEntitiesHeading: string;
      insightsContradictionsHeading: string;
    };
    insights: {
      heading: string;
      description: string;
      empty: string;
      findingsHeading: string;
      claimsHeading: string;
      entitiesHeading: string;
      contradictionsHeading: string;
      jobInfoHeading: string;
      stagesHeading: string;
      confidenceLabel: string;
      statusLabel: string;
      typeLabel: string;
      modelLabel: string;
      providerLabel: string;
      tokensLabel: string;
      costLabel: string;
      createdLabel: string;
      completedLabel: string;
      findingTypes: {
        RISK: string;
        OPPORTUNITY: string;
        WARNING: string;
        OBSERVATION: string;
      };
      claimStatuses: {
        SUPPORTED: string;
        CONTRADICTED: string;
        INCONCLUSIVE: string;
      };
    };
    reports: {
      heading: string;
      description: string;
      empty: string;
      tableHeadType: string;
      tableHeadStage: string;
      tableHeadFormat: string;
      tableHeadSize: string;
      tableHeadDate: string;
      tableHeadJobStatus: string;
      tableHeadActions: string;
      viewCta: string;
      artifactTypes: {
        GENERATED_REPORT: string;
        EXPORT_BUNDLE: string;
        EVIDENCE_MAP: string;
      };
    };
    enquiries: {
      heading: string;
      description: string;
      lockedTitle: string;
      lockedDescription: string;
      introMessage: string;
      sampleQuestionsHeading: string;
      sampleQuestionOne: string;
      sampleQuestionTwo: string;
      sampleQuestionThree: string;
      sendCta: string;
      sendingCta: string;
      investorLabel: string;
      agentLabel: string;
      agentThinking: string;
      sourcesHeading: string;
      errorPrefix: string;
      genericError: string;
      placeholder: string;
    };
    projectCreation: {
      heading: string;
      description: string;
      nameLabel: string;
      namePlaceholder: string;
      filesLabel: string;
      filesHint: string;
      submitCta: string;
      assistanceGoalLabel: string;
      assistanceGoalHint: string;
      noGoalLabel: string;
      noGoalHint: string;
    };
    settings: {
      heading: string;
      description: string;
      firmHeading: string;
      firmDescription: string;
      firmNameLabel: string;
      firmRoleLabel: string;
      firmPlanLabel: string;
      firmBillingLabel: string;
      firmPermissionsLabel: string;
      membersHeading: string;
      membersDescription: string;
      memberEmailLabel: string;
      memberRoleLabel: string;
      memberAddCta: string;
      memberUpdateCta: string;
      auditHeading: string;
      auditDescription: string;
      auditEmpty: string;
      apiKeysHeading: string;
      apiKeysDescription: string;
      encryptionNote: string;
      billingHeading: string;
      billingDescription: string;
      billingPlanLabel: string;
      billingStatusLabel: string;
      billingPeriodEndLabel: string;
      billingUsageHeading: string;
      billingUploadsLabel: string;
      billingRunsLabel: string;
      billingExportsLabel: string;
      billingUpgradeCta: string;
      billingManageCta: string;
      billingNoSubscription: string;
    };
    draft: {
      heading: string;
      description: string;
      noDataHeading: string;
      noDataDescription: string;
      sectionsLabel: string;
      confidenceLabel: string;
      openQuestionsLabel: string;
      openQuestionsHeading: string;
      keyClaimsHeading: string;
      findingsHeading: string;
      gapsHeading: string;
    };
    graphWorkflow: {
      enabledGraphsHeading: string;
      enabledGraphsDescription: string;
      availableGraphsHeading: string;
      noGraphsAvailable: string;
      enableCta: string;
      disableCta: string;
      enabledBadge: string;
      requirementsCount: string;
      goalLabel: string;
      goalNone: string;
      requirementsHeading: string;
      requirementsEmpty: string;
      gapsHeading: string;
      gapsEmpty: string;
      gapPriorityHigh: string;
      gapPriorityMedium: string;
      gapPriorityLow: string;
      mappingStatusOpen: string;
      mappingStatusPartial: string;
      mappingStatusSatisfied: string;
      mappingStatusWaived: string;
      markSatisfiedCta: string;
      markWaivedCta: string;
      outputTemplatesHeading: string;
      outputTemplatesEmpty: string;
      adminHeading: string;
      adminDescription: string;
      adminGraphsHeading: string;
      adminPublishCta: string;
      adminDeprecateCta: string;
      adminStatusDraft: string;
      adminStatusPublished: string;
      adminStatusDeprecated: string;
    };
  };
};
