/**
 * RLS context helpers.
 *
 * Sets PostgreSQL session-local variables that RLS policies read:
 *   app.current_firm_id  — used by firm-scoped policies (Project, EvidenceMapping, AuditLog)
 *   app.current_user_id  — used by user-scoped policies (DiligenceJob and all child tables)
 *
 * Usage — wrap any query that should run under RLS enforcement:
 *
 *   const projects = await withFirmContext({ firmId, userId }, (tx) =>
 *     tx.project.findMany({ where: { firmId } })
 *   );
 *
 * The variables are set with SET LOCAL so they are scoped to the current
 * transaction and automatically cleared when the transaction ends.
 *
 * We also SET LOCAL ROLE app_user to drop the BYPASSRLS privilege that
 * neondb_owner has, so RLS policies are actually enforced.
 *
 * IMPORTANT: The application WHERE clauses still filter by firmId/userId.
 * RLS is the second layer — it catches any missed filter, not the first.
 *
 * NOTE: $executeRawUnsafe is required because PostgreSQL SET does not accept
 * parameterized values ($1 placeholders). The firmId/userId values are
 * internal cuid() strings generated by the application — never user-controlled
 * free-text input — so string interpolation is safe here.
 */

import { db } from "@/lib/db";
import type { PrismaClient } from "@/lib/generated/prisma/client";

// The transaction client type Prisma exposes
type TxClient = Omit<
  PrismaClient,
  "$connect" | "$disconnect" | "$on" | "$transaction" | "$use" | "$extends"
>;

export type RlsContext = {
  firmId: string;
  userId?: string;
};

/**
 * Runs `fn` inside a transaction with RLS session variables set.
 * The callback receives the transaction client — use it for all queries
 * so they run on the same connection as the SET LOCAL statements.
 */
export async function withFirmContext<T>(
  ctx: RlsContext,
  fn: (tx: TxClient) => Promise<T>
): Promise<T> {
  return db.$transaction(async (tx) => {
    // Switch to app_user role which does NOT have BYPASSRLS,
    // so RLS policies are enforced for the duration of this transaction.
    await tx.$executeRawUnsafe(`SET LOCAL ROLE app_user`);
    await tx.$executeRawUnsafe(
      `SET LOCAL "app.current_firm_id" = '${ctx.firmId.replace(/'/g, "''")}'`
    );
    if (ctx.userId) {
      await tx.$executeRawUnsafe(
        `SET LOCAL "app.current_user_id" = '${ctx.userId.replace(/'/g, "''")}'`
      );
    }
    return fn(tx);
  });
}

/**
 * Runs `fn` with only the user context set (for tables scoped by userId only).
 */
export async function withUserContext<T>(
  userId: string,
  fn: (tx: TxClient) => Promise<T>
): Promise<T> {
  return db.$transaction(async (tx) => {
    await tx.$executeRawUnsafe(`SET LOCAL ROLE app_user`);
    await tx.$executeRawUnsafe(
      `SET LOCAL "app.current_user_id" = '${userId.replace(/'/g, "''")}'`
    );
    return fn(tx);
  });
}
